Repository torchgan/torchgan, pull requests merged in 2018-12, with the labels that each got.

#61 Add Feature Matching Generator Loss
  torchgan/losses/__init__.py
  torchgan/losses/featurematching.py
  torchgan/models/acgan.py
  torchgan/models/autoencoding.py
  torchgan/models/conditional.py
  torchgan/models/dcgan.py
  torchgan/models/infogan.py
Labels: awaiting review, enhancement, feature, v0.1

#56 DRAGAN Gradient Penalty
  docs/source/losses.rst
  torchgan/losses/__init__.py
  torchgan/losses/draganpenalty.py
Labels: awaiting review, feature, tests needed, v0.1

#62 Refactors the Trainer API and adds function for cleaner train ops
  README.md
  test/test-trainer.py
  torchgan/losses/auxclassifier.py
  torchgan/losses/boundaryequilibrium.py
  torchgan/losses/loss.py
  torchgan/metrics/classifierscore.py
  torchgan/trainer/trainer.py
Labels: awaiting review, enhancement, high priority

#65 Remove References to Redundant Parameters
  torchgan/losses/auxclassifier.py
  torchgan/losses/boundaryequilibrium.py
  torchgan/losses/draganpenalty.py
  torchgan/losses/featurematching.py
  torchgan/losses/loss.py
  torchgan/losses/wasserstein.py
Labels: awaiting review, v0.1

#66 Fix Gradient Visualization
  torchgan/logging/logger.py
  torchgan/logging/visualize.py
  torchgan/trainer/trainer.py
Labels: awaiting review, high priority, v0.1

#68 Fix logging of incorrect image names
  torchgan/logging/visualize.py
Labels: bug

#54 Add historical averaging
  torchgan/losses/__init__.py
  torchgan/losses/historical.py
Labels: awaiting merge, enhancement, feature, v0.0.2

#69 Add a transposed residual block
  torchgan/layers/residual.py
Labels: awaiting merge, enhancement, high priority

#57 Add EBGAN PT
  docs/source/losses.rst
  torchgan/losses/energybased.py
  torchgan/models/autoencoding.py
Labels: awaiting merge, enhancement, high priority, v0.0.2

#60 Add Virtual Batch Normalization Layer
  torchgan/layers/__init__.py
  torchgan/layers/virtualbatchnorm.py
Labels: awaiting review, enhancement, feature

#59 Add Minibatch Discrimination Layer
  torchgan/layers/__init__.py
  torchgan/layers/minibatchdiscrimination.py
Labels: awaiting review, feature, v0.0.2

#67 Add Tutorials for torchgan
  docs/source/assets/custom_loss_1.png
  docs/source/assets/custom_loss_2.png
  docs/source/assets/cyclegan_1.png
  docs/source/assets/cyclegan_2.png
  docs/source/assets/cyclegan_3.png
  docs/source/assets/cyclegan_4.png
  docs/source/assets/intro_1.png
  docs/source/assets/intro_2.png
  docs/source/assets/sagan_1.png
  docs/source/assets/sagan_2.png
  docs/source/conf.py
  docs/source/index.rst
  docs/source/modules/layers.rst
  docs/source/modules/models.rst
  docs/source/tutorials/custom_loss.rst
  docs/source/tutorials/cyclegan.rst
  docs/source/tutorials/intro.rst
  docs/source/tutorials/sagan.rst
  torchgan/layers/minibatchdiscrimination.py
  torchgan/losses/minimax.py
  tutorials/Custom Losses Tutorial.ipynb
  tutorials/CycleGAN Tutorial.ipynb
  tutorials/Introduction To TorchGAN.ipynb
  tutorials/Self Attention GAN Tutorial.ipynb
Labels: enhancement, high priority, work in progress

#72 Fix the Classifier Score Metric
  torchgan/logging/logger.py
  torchgan/logging/visualize.py
  torchgan/metrics/classifierscore.py
  torchgan/trainer/trainer.py
Labels: awaiting review, bug

#76 Add option to control Discriminator training
  torchgan/trainer/trainer.py
Labels: awaiting review, enhancement
