Repository torchgan/torchgan, pull requests merged in 2018-11, with the labels that each got.

#39 Add gradient logging for Tensorboard
  torchgan/trainer/trainer.py
Labels: awaiting review, enhancement, feature, v0.1

#42 Add Parameter clipping to Wasserstein GAN and fix minor bugs in overriding train ops for losses
  torchgan/losses/boundaryequilibrium.py
  torchgan/losses/energybased.py
  torchgan/losses/leastsquares.py
  torchgan/losses/loss.py
  torchgan/losses/minimax.py
  torchgan/losses/mutualinfo.py
  torchgan/losses/wasserstein.py
Labels: awaiting review, bug, high priority

#41 Generalise Autoencoding Generator and Discriminator to allow arbitrary scaling
  test/test_models.py
  torchgan/models/autoencoding.py
Labels: awaiting review, enhancement, feature, high priority, v0.1

#43 Update loss ops for conditional models
  test/test_models.py
  test/test_trainer.py
  torchgan/losses/boundaryequilibrium.py
  torchgan/losses/loss.py
  torchgan/losses/wasserstein.py
  torchgan/models/autoencoding.py
  torchgan/models/conditional.py
  torchgan/models/dcgan.py
  torchgan/models/model.py
  torchgan/trainer/trainer.py
Labels: awaiting review, feature, high priority, v0.1

#44 Fix the metrics
  torchgan/metrics/classifierscore.py
  torchgan/trainer/trainer.py
Labels: awaiting review, bug, v0.1

#47 Proper device assignment in generated labels for loss ops and image sampling
  torchgan/losses/boundaryequilibrium.py
  torchgan/losses/loss.py
  torchgan/losses/wasserstein.py
  torchgan/trainer/trainer.py
Labels: awaiting review, bug, high priority

#48 Add Auxiliary Classifier GAN Model
  docs/source/losses.rst
  docs/source/models.rst
  test/test_models.py
  test/test_trainer.py
  torchgan/losses/__init__.py
  torchgan/losses/auxclassifier.py
  torchgan/models/__init__.py
  torchgan/models/acgan.py
Labels: feature, v0.1

#52 Add building blocks for Models
  torchgan/layers/__init__.py
  torchgan/layers/denseblock.py
  torchgan/layers/residual.py
  torchgan/layers/selfattention.py
  torchgan/layers/spectralnorm.py
Labels: awaiting review, enhancement, tests needed, work in progress
