Repository torchgan/torchgan, pull requests merged in 2018-10, with the labels that each got.

#31 Add travis support and proper badge links
  .codecov.yml
  .travis.yml
  README.md
Labels: awaiting review

#32 Correct error in BEGAN loss implementation and add an autoencoding discriminator
  test/test_models.py
  torchgan/losses/boundaryequilibrium.py
  torchgan/models/__init__.py
  torchgan/models/autoencoding.py
Labels: awaiting review, high priority, v0.1

#33 Patch for Generalization of Image
  torchgan/trainer/trainer.py
Labels: awaiting review, high priority, v0.1

#34 Extend models to more general input sizes
  test/test_models.py
  torchgan/models/conditional.py
  torchgan/models/dcgan.py
  torchgan/models/infogan.py
Labels: awaiting review, enhancement

#36 Minimal Assumption Trainer
  docs/source/basic_example.rst
  docs/source/losses.rst
  docs/source/models.rst
  docs/source/trainer.rst
  torchgan/losses/boundaryequilibrium.py
  torchgan/losses/loss.py
  torchgan/losses/mutualinfo.py
  torchgan/losses/wasserstein.py
  torchgan/models/autoencoding.py
  torchgan/trainer/trainer.py
Labels: awaiting review, enhancement, feature, high priority, v0.1
